# Uncomment the next line to define a global platform for your project
# platform :ios, '15.1'

target 'Code Sample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Code Sample
  pod 'IQKeyboardManager'
  pod 'PNChart'
  
  

  pod 'AEPTarget'
  pod 'AEPCore'
  pod 'AEPUserProfile'
  pod 'AEPIdentity'
  pod 'AEPSignal'
  pod 'AEPLifecycle'
  pod 'AEPAnalytics'
  pod 'AEPAssurance'
end
